ERROR - 2025-05-19 07:24:06 --> mysqli_sql_exception: Unknown column 'data_user_email' in 'where clause' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(713): CodeIgniter\Model->doFirst()
#6 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(93): CodeIgniter\BaseModel->first()
#7 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
#8 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2025-05-19 07:24:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'data_user_email' in 'where clause'
[Method: POST, Route: verifyOtp]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `data_user_email` = :data_user_email:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 4 APPPATH\Controllers\Home.php(93): CodeIgniter\BaseModel->first()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:24:06 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'data_user_email' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `users`
WHERE `data_user_email` = \'\'
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `users`
WHERE `data_user_email` = \'\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `data_user_email` = :data_user_email:
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 6 APPPATH\Controllers\Home.php(93): CodeIgniter\BaseModel->first()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:24:06 --> [Caused by] mysqli_sql_exception: Unknown column 'data_user_email' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *
FROM `users`
WHERE `data_user_email` = \'\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `users`
WHERE `data_user_email` = \'\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `users`
WHERE `data_user_email` = \'\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `data_user_email` = :data_user_email:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 7 APPPATH\Controllers\Home.php(93): CodeIgniter\BaseModel->first()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-19 07:24:33 --> mysqli_sql_exception: Unknown column 'data_user_email' in 'where clause' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(713): CodeIgniter\Model->doFirst()
#6 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(93): CodeIgniter\BaseModel->first()
#7 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
#8 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2025-05-19 07:24:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'data_user_email' in 'where clause'
[Method: POST, Route: verifyOtp]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `data_user_email` = :data_user_email:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 4 APPPATH\Controllers\Home.php(93): CodeIgniter\BaseModel->first()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:24:33 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'data_user_email' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `users`
WHERE `data_user_email` = \'\'
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `users`
WHERE `data_user_email` = \'\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `data_user_email` = :data_user_email:
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 6 APPPATH\Controllers\Home.php(93): CodeIgniter\BaseModel->first()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:24:33 --> [Caused by] mysqli_sql_exception: Unknown column 'data_user_email' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *
FROM `users`
WHERE `data_user_email` = \'\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `users`
WHERE `data_user_email` = \'\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `users`
WHERE `data_user_email` = \'\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `data_user_email` = :data_user_email:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 7 APPPATH\Controllers\Home.php(93): CodeIgniter\BaseModel->first()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:35:11 --> ErrorException: Undefined array key "id"
[Method: POST, Route: verifyOtp]
in APPPATH\Controllers\Home.php on line 97.
 1 APPPATH\Controllers\Home.php(97): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id"', 'D:\\xampp\\htdocs\\Psits_System\\app\\Controllers\\Home.php', 97)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:36:38 --> ErrorException: Undefined array key "data-user-id"
[Method: POST, Route: verifyOtp]
in APPPATH\Controllers\Home.php on line 97.
 1 APPPATH\Controllers\Home.php(97): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "data-user-id"', 'D:\\xampp\\htdocs\\Psits_System\\app\\Controllers\\Home.php', 97)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-19 07:38:17 --> mysqli_sql_exception: Unknown column 'users.id' in 'where clause' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` ...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(1027): CodeIgniter\Model->doUpdate(Array, Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(863): CodeIgniter\BaseModel->update(Array, Array)
#7 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(97): CodeIgniter\Model->update('49', Array)
#8 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-05-19 07:38:17 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
[Method: POST, Route: verifyOtp]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:38:17 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:38:17 --> [Caused by] mysqli_sql_exception: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-19 07:38:58 --> mysqli_sql_exception: Unknown column 'users.id' in 'where clause' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` ...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(1027): CodeIgniter\Model->doUpdate(Array, Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(863): CodeIgniter\BaseModel->update(Array, Array)
#7 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(97): CodeIgniter\Model->update('49', Array)
#8 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-05-19 07:38:58 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
[Method: POST, Route: verifyOtp]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:38:58 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:38:58 --> [Caused by] mysqli_sql_exception: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-19 07:38:59 --> mysqli_sql_exception: Unknown column 'users.id' in 'where clause' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` ...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(1027): CodeIgniter\Model->doUpdate(Array, Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(863): CodeIgniter\BaseModel->update(Array, Array)
#7 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(97): CodeIgniter\Model->update('49', Array)
#8 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-05-19 07:38:59 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
[Method: POST, Route: verifyOtp]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:38:59 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:38:59 --> [Caused by] mysqli_sql_exception: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-19 07:39:46 --> mysqli_sql_exception: Unknown column 'users.id' in 'where clause' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` ...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(1027): CodeIgniter\Model->doUpdate(Array, Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(863): CodeIgniter\BaseModel->update(Array, Array)
#7 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(97): CodeIgniter\Model->update('49', Array)
#8 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-05-19 07:39:46 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
[Method: POST, Route: verifyOtp]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:39:46 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:39:46 --> [Caused by] mysqli_sql_exception: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-19 07:39:48 --> mysqli_sql_exception: Unknown column 'users.id' in 'where clause' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` ...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(1027): CodeIgniter\Model->doUpdate(Array, Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(863): CodeIgniter\BaseModel->update(Array, Array)
#7 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(97): CodeIgniter\Model->update('49', Array)
#8 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-05-19 07:39:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
[Method: POST, Route: verifyOtp]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:39:48 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:39:48 --> [Caused by] mysqli_sql_exception: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-19 07:41:17 --> mysqli_sql_exception: Unknown column 'users.id' in 'where clause' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` ...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(1027): CodeIgniter\Model->doUpdate(Array, Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(863): CodeIgniter\BaseModel->update(Array, Array)
#7 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(97): CodeIgniter\Model->update('49', Array)
#8 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-05-19 07:41:17 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
[Method: POST, Route: verifyOtp]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:41:17 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:41:17 --> [Caused by] mysqli_sql_exception: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-19 07:41:19 --> mysqli_sql_exception: Unknown column 'users.id' in 'where clause' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` ...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(1027): CodeIgniter\Model->doUpdate(Array, Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(863): CodeIgniter\BaseModel->update(Array, Array)
#7 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(97): CodeIgniter\Model->update('49', Array)
#8 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-05-19 07:41:19 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
[Method: POST, Route: verifyOtp]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:41:19 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:41:19 --> [Caused by] mysqli_sql_exception: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-19 07:41:20 --> mysqli_sql_exception: Unknown column 'users.id' in 'where clause' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` ...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(1027): CodeIgniter\Model->doUpdate(Array, Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(863): CodeIgniter\BaseModel->update(Array, Array)
#7 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(97): CodeIgniter\Model->update('49', Array)
#8 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-05-19 07:41:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
[Method: POST, Route: verifyOtp]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:41:20 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:41:20 --> [Caused by] mysqli_sql_exception: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-19 07:41:22 --> mysqli_sql_exception: Unknown column 'users.id' in 'where clause' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` ...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(1027): CodeIgniter\Model->doUpdate(Array, Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(863): CodeIgniter\BaseModel->update(Array, Array)
#7 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(97): CodeIgniter\Model->update('49', Array)
#8 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-05-19 07:41:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
[Method: POST, Route: verifyOtp]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:41:22 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:41:22 --> [Caused by] mysqli_sql_exception: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-19 07:41:23 --> mysqli_sql_exception: Unknown column 'users.id' in 'where clause' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` ...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(1027): CodeIgniter\Model->doUpdate(Array, Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(863): CodeIgniter\BaseModel->update(Array, Array)
#7 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(97): CodeIgniter\Model->update('49', Array)
#8 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-05-19 07:41:23 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
[Method: POST, Route: verifyOtp]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:41:23 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:41:23 --> [Caused by] mysqli_sql_exception: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'49\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('49', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-19 07:42:03 --> mysqli_sql_exception: Unknown column 'users.id' in 'where clause' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` ...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(1027): CodeIgniter\Model->doUpdate(Array, Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(863): CodeIgniter\BaseModel->update(Array, Array)
#7 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(97): CodeIgniter\Model->update('50', Array)
#8 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-05-19 07:42:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
[Method: POST, Route: verifyOtp]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('50', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:42:03 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'50\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'50\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('50', [...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-19 07:42:03 --> [Caused by] mysqli_sql_exception: Unknown column 'users.id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'50\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'50\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` SET `data-user-otp` = NULL, `data-user-otp-expires` = NULL
WHERE `users`.`id` IN (\'50\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `data-user-otp` = :data-user-otp:, `data-user-otp-expires` = :data-user-otp-expires:
WHERE `users`.`id` IN :users.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Home.php(97): CodeIgniter\Model->update('50', [...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->verifyOtp()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
